from fractions import Fraction
from itertools import product as iproduct

from crowdmath2026.rationals import fraction_to_str, fraction_sort_key


def prime_factors(n: int) -> set[int]:
    """Return the set of distinct prime divisors of a positive integer n."""
    if n <= 1:
        return set()
    primes: set[int] = set()
    d = 2
    while d * d <= n:
        if n % d == 0:
            primes.add(d)
            while n % d == 0:
                n //= d
        d += 1
    if n > 1:
        primes.add(n)
    return primes


def theoretical_units_n0q(
    q: Fraction,
    max_abs_exponent: int,
) -> set[Fraction]:
    """Return a finite bounded sample of theoretical units of (N0[q] \\ {0}, *).

    Based on Exercise 1.7 (Resource 1):
    - q in N (denominator 1):    units = {1}
    - q = 1/n (numerator 1):     units generated by primes dividing n,
                                  within exponent bound [-max_abs_exponent, max_abs_exponent]
    - q = a/b with a,b > 1:     units = {1}

    For the q=1/n case, the unit group of (N0[1/n] \\ {0}, *) consists of
    all positive rationals whose numerator and denominator are products of
    primes dividing n. This function returns the finite sample bounded by
    the given exponent range.

    All arithmetic is exact via fractions.Fraction.
    """
    a, b = q.numerator, q.denominator

    if b == 1:
        return {Fraction(1)}

    if a == 1:
        n = b
        primes = sorted(prime_factors(n))
        if not primes:
            return {Fraction(1)}
        exponents_range = range(-max_abs_exponent, max_abs_exponent + 1)
        units: set[Fraction] = set()
        for exps in iproduct(exponents_range, repeat=len(primes)):
            val = Fraction(1)
            for p, e in zip(primes, exps):
                if e >= 0:
                    val *= Fraction(p ** e)
                else:
                    val *= Fraction(1, p ** (-e))
            units.add(val)
        return units

    return {Fraction(1)}


def find_multiplicative_inverse_in_sample(
    x: Fraction,
    sample: set[Fraction],
) -> Fraction | None:
    """Return 1/x if it is present in the sample, otherwise None.

    This is an O(1) lookup using the set structure.
    A None result means the inverse was not found in the bounded sample;
    it does not prove that x is not a unit in the infinite monoid.
    """
    if x == Fraction(0):
        return None
    inverse = Fraction(1) / x
    return inverse if inverse in sample else None


def classify_units_in_sample(
    sample: set[Fraction],
) -> dict[Fraction, Fraction | None]:
    """For each nonzero element of the sample, check whether its inverse is also in the sample.

    Returns a dict mapping each nonzero element to its inverse in the sample,
    or None if no inverse was found. Zero is excluded from multiplicative checks.

    This is a bounded result: an element may be a theoretical unit even if
    its inverse is not present in the bounded sample.
    """
    zero = Fraction(0)
    result: dict[Fraction, Fraction | None] = {}
    nonzero = {x for x in sample if x != zero}
    for x in nonzero:
        result[x] = find_multiplicative_inverse_in_sample(x, nonzero)
    return result


def compare_units_to_theory(
    sample_units: set[Fraction],
    theoretical_units: set[Fraction],
) -> dict[str, set[Fraction]]:
    """Compare bounded sample units to the theoretical unit set.

    Returns:
      true_positives          : in both sample_units and theoretical_units
      false_positives         : in sample_units but not in theoretical_units
      missed_theoretical_units: in theoretical_units but not in sample_units

    False positives occur when a non-unit element has its inverse present
    in the bounded sample by coincidence. Missed theoretical units occur when
    the inverse of a theoretical unit lies outside the bounded sample.
    """
    true_positives = sample_units & theoretical_units
    false_positives = sample_units - theoretical_units
    missed = theoretical_units - sample_units

    return {
        "true_positives": true_positives,
        "false_positives": false_positives,
        "missed_theoretical_units": missed,
    }
